import type { Tasker } from "@/types";

export const taskers: Tasker[] = [
  {
    id: "tsk-marcus",
    name: "Marcus Johnson",
    avatar: "MJ",
    rating: 4.9,
    completedTasks: 312,
    hourlyRate: 42,
    services: ["furniture-assembly", "handyman"],
    distance: 2.4,
    availability: [
      { date: "today", start: "16:00", end: "18:00" },
      { date: "tomorrow", start: "10:00", end: "16:00" },
    ],
    bio: "Flat-pack specialist. Beds, desks, and wardrobes same-day.",
  },
  {
    id: "tsk-sarah",
    name: "Sarah Williams",
    avatar: "SW",
    rating: 4.8,
    completedTasks: 184,
    hourlyRate: 48,
    services: ["home-cleaning", "packing-unpacking"],
    distance: 1.8,
    availability: [
      { date: "today", start: "17:00", end: "20:00" },
      { date: "tomorrow", start: "09:00", end: "15:00" },
    ],
    bio: "Detail-oriented cleaner who times jobs around other household work.",
  },
  {
    id: "tsk-david",
    name: "David Chen",
    avatar: "DC",
    rating: 4.9,
    completedTasks: 421,
    hourlyRate: 55,
    services: ["tv-mounting", "electrical", "handyman"],
    distance: 3.1,
    availability: [
      { date: "today", start: "18:30", end: "20:30" },
      { date: "tomorrow", start: "12:00", end: "18:00" },
    ],
    bio: "TV mounting and tidy cable runs. Licensed for light electrical.",
  },
  {
    id: "tsk-james",
    name: "James Wilson",
    avatar: "JW",
    rating: 4.8,
    completedTasks: 267,
    hourlyRate: 45,
    services: ["furniture-assembly", "moving-help"],
    distance: 3.6,
    availability: [
      { date: "today", start: "16:30", end: "19:00" },
      { date: "saturday", start: "09:00", end: "17:00" },
    ],
    bio: "Reliable assembler who can also help with the heavy lift.",
  },
  {
    id: "tsk-priya",
    name: "Priya Patel",
    avatar: "PP",
    rating: 4.9,
    completedTasks: 203,
    hourlyRate: 50,
    services: ["home-cleaning"],
    distance: 2.1,
    availability: [
      { date: "today", start: "15:00", end: "19:00" },
      { date: "tomorrow", start: "11:00", end: "16:00" },
    ],
    bio: "Move-in and event cleaning with eco-friendly products.",
  },
  {
    id: "tsk-luis",
    name: "Luis Ramirez",
    avatar: "LR",
    rating: 4.7,
    completedTasks: 156,
    hourlyRate: 40,
    services: ["moving-help", "packing-unpacking"],
    distance: 4.2,
    availability: [
      { date: "saturday", start: "08:00", end: "16:00" },
      { date: "sunday", start: "09:00", end: "14:00" },
    ],
    bio: "Weekend moving crews and careful box handling.",
  },
  {
    id: "tsk-emma",
    name: "Emma Thompson",
    avatar: "ET",
    rating: 4.8,
    completedTasks: 98,
    hourlyRate: 38,
    services: ["packing-unpacking", "delivery"],
    distance: 2.8,
    availability: [
      { date: "saturday", start: "10:00", end: "18:00" },
      { date: "today", start: "14:00", end: "18:00" },
    ],
    bio: "Organized packer who labels rooms and fragile items.",
  },
  {
    id: "tsk-omar",
    name: "Omar Hassan",
    avatar: "OH",
    rating: 4.9,
    completedTasks: 340,
    hourlyRate: 52,
    services: ["handyman", "plumbing"],
    distance: 2.9,
    availability: [
      { date: "today", start: "13:00", end: "17:00" },
      { date: "tomorrow", start: "09:00", end: "13:00" },
    ],
    bio: "Fixes the list: hanging, patching, and small plumbing.",
  },
  {
    id: "tsk-aisha",
    name: "Aisha Brooks",
    avatar: "AB",
    rating: 4.7,
    completedTasks: 121,
    hourlyRate: 42,
    services: ["home-cleaning", "yard-work"],
    distance: 5.1,
    availability: [
      { date: "today", start: "11:00", end: "16:00" },
      { date: "sunday", start: "10:00", end: "15:00" },
    ],
    bio: "Indoor clean plus outdoor tidy if you need both.",
  },
  {
    id: "tsk-kenji",
    name: "Kenji Nakamura",
    avatar: "KN",
    rating: 4.8,
    completedTasks: 289,
    hourlyRate: 58,
    services: ["tv-mounting", "electrical"],
    distance: 4.4,
    availability: [
      { date: "today", start: "19:00", end: "21:00" },
      { date: "tomorrow", start: "15:00", end: "19:00" },
    ],
    bio: "Precision mounting on plaster and brick.",
  },
  {
    id: "tsk-sofia",
    name: "Sofia Rossi",
    avatar: "SR",
    rating: 4.6,
    completedTasks: 87,
    hourlyRate: 40,
    services: ["furniture-assembly", "packing-unpacking"],
    distance: 1.5,
    availability: [
      { date: "today", start: "12:00", end: "16:00" },
      { date: "saturday", start: "09:00", end: "13:00" },
    ],
    bio: "Nearby assembler, great for compact apartments.",
  },
  {
    id: "tsk-tyler",
    name: "Tyler Brooks",
    avatar: "TB",
    rating: 4.8,
    completedTasks: 174,
    hourlyRate: 36,
    services: ["yard-work", "moving-help"],
    distance: 6.2,
    availability: [
      { date: "saturday", start: "08:00", end: "14:00" },
      { date: "sunday", start: "08:00", end: "12:00" },
    ],
    bio: "Outdoor cleanup and muscle for bulky items.",
  },
  {
    id: "tsk-maya",
    name: "Maya Singh",
    avatar: "MS",
    rating: 4.9,
    completedTasks: 412,
    hourlyRate: 32,
    services: ["delivery", "packing-unpacking"],
    distance: 3.3,
    availability: [
      { date: "today", start: "12:00", end: "20:00" },
      { date: "tomorrow", start: "10:00", end: "18:00" },
    ],
    bio: "Same-day delivery and party supply runs.",
  },
  {
    id: "tsk-chris",
    name: "Chris Nguyen",
    avatar: "CN",
    rating: 4.7,
    completedTasks: 198,
    hourlyRate: 60,
    services: ["electrical", "tv-mounting"],
    distance: 4.8,
    availability: [
      { date: "tomorrow", start: "09:00", end: "14:00" },
      { date: "today", start: "16:00", end: "19:00" },
    ],
    bio: "Licensed electrician for fixtures and safe TV circuits.",
  },
  {
    id: "tsk-hannah",
    name: "Hannah Cole",
    avatar: "HC",
    rating: 4.6,
    completedTasks: 76,
    hourlyRate: 44,
    services: ["home-cleaning"],
    distance: 3.9,
    availability: [
      { date: "today", start: "18:00", end: "21:00" },
      { date: "tomorrow", start: "13:00", end: "17:00" },
    ],
    bio: "Evening cleans when the rest of the plan is already booked.",
  },
  {
    id: "tsk-andre",
    name: "Andre Williams",
    avatar: "AW",
    rating: 4.9,
    completedTasks: 355,
    hourlyRate: 54,
    services: ["plumbing", "handyman"],
    distance: 2.6,
    availability: [
      { date: "today", start: "10:00", end: "15:00" },
      { date: "tomorrow", start: "10:00", end: "16:00" },
    ],
    bio: "Leaks, faucets, and the jobs you do not want to guess at.",
  },
  {
    id: "tsk-lena",
    name: "Lena Kowalski",
    avatar: "LK",
    rating: 4.8,
    completedTasks: 229,
    hourlyRate: 46,
    services: ["furniture-assembly", "handyman"],
    distance: 3.4,
    availability: [
      { date: "today", start: "15:00", end: "19:00" },
      { date: "saturday", start: "11:00", end: "17:00" },
    ],
    bio: "Fast IKEA builds with leftover hardware bagged and labeled.",
  },
  {
    id: "tsk-jordan",
    name: "Jordan Lee",
    avatar: "JL",
    rating: 4.7,
    completedTasks: 143,
    hourlyRate: 38,
    services: ["moving-help", "delivery"],
    distance: 5.5,
    availability: [
      { date: "saturday", start: "07:00", end: "15:00" },
      { date: "sunday", start: "08:00", end: "14:00" },
    ],
    bio: "Truck-friendly mover for weekend relocations.",
  },
  {
    id: "tsk-fatima",
    name: "Fatima Al-Sayed",
    avatar: "FA",
    rating: 4.8,
    completedTasks: 167,
    hourlyRate: 41,
    services: ["packing-unpacking", "home-cleaning"],
    distance: 2.2,
    availability: [
      { date: "saturday", start: "09:00", end: "15:00" },
      { date: "today", start: "13:00", end: "17:00" },
    ],
    bio: "Unpack then wipe down so the space is livable the same day.",
  },
  {
    id: "tsk-ryan",
    name: "Ryan O'Connor",
    avatar: "RO",
    rating: 4.6,
    completedTasks: 92,
    hourlyRate: 35,
    services: ["yard-work", "handyman"],
    distance: 7.1,
    availability: [
      { date: "saturday", start: "08:00", end: "12:00" },
      { date: "sunday", start: "09:00", end: "13:00" },
    ],
    bio: "Yard resets and outdoor hardware installs.",
  },
  {
    id: "tsk-nina",
    name: "Nina Volkov",
    avatar: "NV",
    rating: 4.9,
    completedTasks: 278,
    hourlyRate: 34,
    services: ["delivery", "moving-help"],
    distance: 4.0,
    availability: [
      { date: "today", start: "11:00", end: "19:00" },
      { date: "saturday", start: "10:00", end: "18:00" },
    ],
    bio: "Punctual delivery for decorations, food, and last-minute supplies.",
  },
  {
    id: "tsk-carlos",
    name: "Carlos Mendes",
    avatar: "CM",
    rating: 4.8,
    completedTasks: 201,
    hourlyRate: 56,
    services: ["plumbing", "electrical"],
    distance: 3.7,
    availability: [
      { date: "tomorrow", start: "08:00", end: "14:00" },
      { date: "today", start: "09:00", end: "13:00" },
    ],
    bio: "Cross-trained on water and power so one visit covers both.",
  },
];

export function getTaskerById(id: string) {
  return taskers.find((tasker) => tasker.id === id);
}

export function getTaskerByName(name: string) {
  return taskers.find((tasker) => tasker.name === name);
}
